[project]
org-name= "ballerinax"
version= "0.9.0"
license= ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Azure", "Active", "Directory", "ActiveDirectory", "Microsoft"]
repository = "https://github.com/ballerina-platform/module-ballerinax-azure.ad"
