name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Ballerina Build
        uses: ballerina-platform/ballerina-action/@master
        with:
          args:
            build -c --skip-tests azure.ad --b7a.config.file=src/azure.ad/tests/resources/azure-ad-config.toml
